name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - ipynb
  - ipywidgets
  - scipy
  - cycler
  - ipympl
